project:
  type: website

website:
  title: "RJ Bingham"
  description: "Protein biochemist / Educator"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
